/** @type {import('tailwindcss').Config} */
const withAnimations = require("animated-tailwindcss");
module.exports = withAnimations({
  content: [
    "./_includes/**/*.{html,njk}",
    "./archives/**/*.{html,njk}",
    "./pages/**/*.{html,njk}",
    "./**/*.{njk}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--theme-background)",
        backgroundVariant: "var(--theme-backgroundVariant)",
        onBackground: "var(--theme-on-background)",
        onBackgroundVariant: "var(--theme-on-backgroundVariant)",
        primary: "var(--theme-primary)",
        primaryVariant: "var(--theme-primaryVariant)",
        onPrimary: "var(--theme-on-primary)",
        onPrimaryVariant: "var(--theme-on-primaryVariant)",
        secondary: "var(--theme-secondary)",
        onSecondary: "var(--theme-on-secondary)",
        secondaryVariant: "var(--theme-secondary-variant)",
        surface: "var(--theme-surface)",
        onSurface: "var(--theme-on-surface)",
        onSurfaceVariant: "var(--theme-on-surfaceVariant)",
        error: "var(--theme-error)",
      },
      fontFamily: {
        Roboto: ["Roboto"],
        Lato: ["Lato"],
        Sora: ["Sora"],
        Poppins: ["Poppins"],
        Raleway: ["Raleway"],
        Oswald: ["Oswald"],
        "Montserrat-Alternates": ["Montserrat Alternates"],
        Anton: ["Anton"],
        Archivo: ["Archivo"],
        "Encode-Sans": ["Encode Sans"],
        Epilogue: ["Epilogue"],
        "Work-Sans": ["Work Sans"],
        Lora: ["Lora"],
        "Andada-Pro": ["Andada Pro"],
        Hahmlet: ["Hahmlet"],
        Cormorant: ["Cormorant"],
        "Old-Standard-TT": ["Old Standard TT"],
        "Playfair-Display": ["Playfair Display"],
        Anton: ["Anton"],
        Archivo: ["Archivo"],
        "JetBrains Mono": ["JetBrains Mono"],
        "Source-Code-Pro": ["Source Code Pro"],
        "Noto-Serif-Bengali": ["Noto Serif Bengali"],
        "Baloo-Da-2": ["Baloo Da 2"],
        Galada: ["Galada"],
        "Mrs-Saint-Delafield": ["Mrs Saint Delafield"],
        Amita: ["Amita"],
        Cookie: ["Cookie"],
        "Rock-Salt": ["Rock Salt"],
        Sacramento: ["Sacramento"],
        Hurricane: ["Hurricane"],
        Stalemate: ["Stalemate"],
        "Ms-Madi": ["Ms Madi"],
        "Kolker-Brush": ["Kolker Brush"],
      },
    },
    container: {
      center: true,
      padding: "1rem",
      // screens: {
      //   'lg': '1024px',
      //   'xl': '1024px',
      //   '2xl': '1024px',
      // }
    },
  },
  plugins: [],
});
